const mongoose = require('mongoose');

const PlayerSchema = new mongoose.Schema({
  player: {
    type: String,
    index: { unique: true }
  },
  code: Number,
  pos: String,
  club: String,
  new: String,
  apps: Number,
  subs: Number,
  gls: Number,
  asts: Number,
  mom: Number,
  cs: Number,
  con: Number,
  pensv: Number,
  ycard: Number,
  rcard: Number,
  change: Number,
  gw35: Number,
  gw34: Number,
  gw33: Number,
  gw32: Number,
  gw31: Number,
  gw30: Number,
  gw29: Number,
  gw28: Number,
  gw27: Number,
  gw26: Number,
  gw25: Number,
  gw24: Number,
  gw23: Number,
  gw22: Number,
  gw21: Number,
  gw20: Number,
  gw19: Number,
  gw18: Number,
  gw17: Number,
  gw16: Number,
  gw15: Number,
  gw14: Number,
  gw13: Number,
  gw12: Number,
  gw11: Number,
  gw10: Number,
  gw9: Number,
  gw8: Number,
  gw7: Number,
  gw6: Number,
  gw5: Number,
  gw4: Number,
  gw3: Number,
  gw2: Number,
  gw1: Number,
  gw0: Number
});


module.exports = mongoose.model('Players', PlayerSchema);
